version: "3.9"

services:
  front-end-app:
    container_name: front-end-app
    image: frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    # environment:
    #   - FRONTEND_APP_VERSION=${FRONTEND_APP_VERSION:-latest}  # Use the default value 'latest' if not provided :${FRONTEND_APP_VERSION:-latest}


  # selenium-tests:
  #   container_name: selenium-tests
  #   image: frontend-selenium-image
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-selenium
  #   depends_on:
  #     - front-end-app
  #   environment:
  #     - SELENIUM_HOST=front-end-app
  #     - SELENIUM_PORT=8080